---
title: "Econ and Happiness Report"
author: "Bruno, Grace, Jennifer, Tony"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
source("analysis.R")
```

## Problem Domain Description



### Analysis Questions

We gathered indicators of interest from the World Bank and gathered World Happiness data. Our goal is to compare our economic indicators with variables from the World Happiness report. The world happiness report presents global data on national happiness that shows how factors such as government debt and health spending can impact subjective evaluations on the quality of life. The World Bank is a data set of indicators, or variables that can indicate the economic status of a region. Between the two of these data sets, we can determine the relationship between factors that determine economic status and factors that determine happiness. The indicators we chose were health expenditure, primary education enrollment, years of compulsory education, central government debt, and foreign direct investment. We compared these indicators to factors that contribute to happiness such as life expectancy, reported happiness, change in reported happiness, perceptions of corruption, and democratic quality. We want to find the relationships between the economic variables and factors to show if there is a strong correlation between an action and the outcome. We find this problem domain interesting and necessary to explore because the the outcome may indicate the amount of resources that a government needs to dedicate to a particular area.

In order to determine the relationship between economic factors and the factors that determine happiness, we will investigate four main analysis questions:

* Does a country's education determine or influence the happiness of its citizens?

The answer to this question is important since it will inform a country's decision to invest in education spending if it is concerned about the happiness of its citizens. By determining the correlation, or lack therof, between the World Bank's economic factors on education and the UN's factors of happiness, we can gain insight into whther or not education investment is the proper course of action for raising citizen happiness.

* Is there a correlation between health expenditure and healthy life expectancy?

The result of this question will allow the country to know if they should focus more of resources to create better health outcomes for the population. The visual representation created from comparing average health expenditure to life expentancy will demonstrate whether there is a relationship between the two variables of interest. 

* How does the amount of government debt in the US affect the perceptions of corruption?

Figuring out if there is a certain relationship between the debt and the perceptions of corruption in the United States could potentially help us resolve the trust issues people might have against the government. By taking a look at the correlation and relationship between the two, we can see if the amount of debt plays a role in the perceptions of corruption and take action on reducing, or perhaps increasing, debt to mend or establish trust in the nation, and further contribute to the increase in happiness.

* QUESTION 4



## Data Description



## Specific Question Analyses

